# language: csharp
# solution: ./demos/MSTest-visual-studio-demo/Bank.sln
# dotnet: 2.0.0
# install:
#   - nuget restore ./demos/MSTest-visual-studio-demo/Bank.sln
#   - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Debug ./demos/MSTest-visual-studio-demo/Bank.sln
#   - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./demos/MSTest-visual-studio-demo/BankTest/bin/Debug/BankTest.dll

# sudo: required
# language: csharp
# mono: none
# dotnet: 2.0.0
# script:
#  - cd ./demos/xunit-net-core-demo/
#  - dotnet build
#  - dotnet xunit

matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
      script:
        - cd ./demos/python-pytest-demo
        - python --version
        - pytest -v

    - language: csharp
      mono: none
      dotnet: 2.0.0
      script:
        - cd ./demos/xunit-net-core-demo/
        - dotnet build
        - dotnet xunit


    - language: node_js
      node_js:
        - "8"
        - "7"
        - "node"

      script:
        - cd ./demos/nodejs-mocha-demo/
        - npm install    
        - npm test
      after_success:
        - npm run coverage
      deploy:
        provider: azure_web_apps
        verbose: true
        username: liuning0820       # If AZURE_WA_USERNAME isn't set
        password: 1234ABcd   # If AZURE_WA_PASSWORD isn't set
        site: azure-deployment-nodejs-app       # If AZURE_WA_SITE isn't set



