language: csharp
solution: ./demos/MSTest-visual-studio-demo/Bank.sln
install:
  - nuget restore ./demos/MSTest-visual-studio-demo/Bank.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./demos/MSTest-visual-studio-demo/Bank.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./demos/MSTest-visual-studio-demo/BankTest/bin/Release/BankTest.dll