# language: csharp
# solution: ./demos/MSTest-visual-studio-demo/Bank.sln
# dotnet: 2.0.0
# install:
#   - nuget restore ./demos/MSTest-visual-studio-demo/Bank.sln
#   - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Debug ./demos/MSTest-visual-studio-demo/Bank.sln
#   - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./demos/MSTest-visual-studio-demo/BankTest/bin/Debug/BankTest.dll

sudo: required
language: csharp
mono: none
dotnet: 2.0.3
script:
 - dotnet restore
 - cd ./demos/xunit-net-core-demo/
 - dotnet build
 - dotnet test