# language: csharp
# solution: ./demos/MSTest-visual-studio-demo/Bank.sln
# dotnet: 2.0.0
# install:
#   - nuget restore ./demos/MSTest-visual-studio-demo/Bank.sln
#   - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Debug ./demos/MSTest-visual-studio-demo/Bank.sln
#   - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./demos/MSTest-visual-studio-demo/BankTest/bin/Debug/BankTest.dll

sudo: required
language: csharp
language: python
mono: none
dotnet: 2.0.0

python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install pytest


script:
 - cd ./demos/xunit-net-core-demo/
 - dotnet build
 - dotnet xunit
script:
  - cd ../demos/python-pytest-demo
  - pytest -v
